# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    此处用docker 的话如果是docker内部的mysql则可以使用 mysql的容器服务名/Linux的ip地址(使用命令查询容器ip地址： docker inspect 容器id )
    url: jdbc:mysql://192.168.253.128:3306/usercenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0