# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    此处用docker 的话如果是docker内部的mysql则可以使用localhost ，
#    url: jdbc:mysql://localhost:3306/usercenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
#    此处用docker 如果是宿主机的mysql 则需要指定ip地址
    url: jdbc:mysql://172.17.0.2:3306/usercenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Sz10231314@
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0