# mac docker线上配置文件  保持启动项目中的Dockerfile是否为最新版本！
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    此处用docker 的话mysql则可以使用 本机ip地址进行连接
    url: jdbc:mysql://192.168.6.190:3306/usercenter?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Sz10231314@
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0